### ISSUE TITLE
Log files filled with same log messages

### ISSUE THREAD

**Issue by jitendrapurohit** [agileware/au.com.agileware.ewayrecurring#8]
seeing a lot of similar messages in the log files. With log viewer ext, this fills up the whole page - 

![image](https://user-images.githubusercontent.com/5929648/86206789-d31d1180-bb8a-11ea-9c2e-bcd28866129a.png)

Seems to be from https://github.com/agileware/au.com.agileware.ewayrecurring/blob/master/eWAYRecurring.process.inc#L53. I see most of the log statements are already commented in the file. Was this left out for any specific reason?

**Comment by agileware-fj** [comment]
I believe this one was in there because I couldn't see how to return information about how many recurring payments had been processed to the job log for handle_payment_cron.
I think the conclusion there is that other recurring payment processors just implement their own job and use the return success method, and we should probably do the same here.

Anyway, this information isn't that important, I'll remove it.
